### ISSUE TITLE
Feature Request: Add the ability to use pop-up from other places

### ISSUE THREAD

**Issue by tschoiss** [Clooos/Bubble-Card#122]
I really like the Bubble Card, but I don't like to have all my pop-ups "hidden" on the same page where I use them. So please add the ability to use pop-up cards from other places. 
E.g. I have my main page "main" and a page "pop-ups". I want to call the a pop-up from the main page `pop-ups#pop1`. The pop1 should than open on the main page. If I try this now, it will pop up AND navigate to the page.

**Comment by Clooos** [comment]
Hi and thanks for your feedback! It's kinda working if you set your navigation path to `pop-ups#pop1?` (with the `?` at the end) and also add `back_open: true` to your pop-ups, but for some reasons it's only working the second time you click on that button (I will try to fix that). 

But it's not my priority since the main goal of Bubble Card is to have everything on one page, the effect is not the same on different pages. When you use mainly Bubble Card into your pop-ups it's incredibly fast and it's not important to have multiple views (but that's only my opinion). I will add more cards types in the future so that people can have almost 100% Bubble Card pop-ups.

**Comment by tschoiss** [comment]
Thanks for the fast answer. I tried the `?` at the end and also set `back_open: true` to the pop-up I tried, but it also opend on the other page. 

I also try to have one page. But for me it gets too messy with some pop-ups lying around. So I wanted to group them in hidden subpages and call it from my main page.

**Comment by Clooos** [comment]
Yes it will indeed open in an other page that way, it's not possible to do this in a different way right now, and maybe never because of how the pop-ups works. But I will probably add a template feature in the future.

**Comment by n00bcodr** [comment]
Hi @Clooos 

I stumbled upon this beautiful card today and was wondering about the same issue. 

I used the ? and also ahve back_open set to true, but it still wont go back to the view once I close the popup.
