### ISSUE TITLE
Feature Request: Ability to use occupancy sensor. 

### ISSUE THREAD

**Issue by grilledbacon32** [Clooos/Bubble-Card#16]
It would be nice to be able to use occupancy sensors instead of just motion sensors for the auto sort.

**Comment by Clooos** [comment]
If your occupancy sensors are binary_sensor it should work, if it's not the case can you tell me more about that sensors?

**Comment by grilledbacon32** [comment]
> If your occupancy sensors are binary_sensor it should work, if it's not the case can you tell me more about that sensors?

Hi! So, I'm using the Screek Human Sensor 2A and they are just 'sensors'. 

![image](https://github.com/Clooos/Bubble-Card/assets/25890648/99a5188e-c250-4195-a8a5-e341bf382f46)

https://docs.screek.io/2a

**Comment by Clooos** [comment]
I'm not sure how you are using it for triggering your automations, but I guess that you are using its attributes, if so I will not be able to do that because there is no last_changed time for attributes (this how the re-order works). The solution would be to create template binary_sensors for each rooms you have.

**Comment by grilledbacon32** [comment]
Ahh good to know! I didn't realize you were using last_changed. Thank you for that info! I'll use that solution.
