### ISSUE TITLE
100% width dont work on desktop 

### ISSUE THREAD

**Issue by nelsonamen** [Clooos/Bubble-Card#27]
Hi
![16936052675056510038293356947227](https://github.com/Clooos/Bubble-Card/assets/5807434/c5cd154f-5326-49af-9304-02b7f82c7dd4)

100% width dont work on desktop with no side bar 
![16936053324544638717700362654677](https://github.com/Clooos/Bubble-Card/assets/5807434/a359ac4e-b93b-4846-9e38-1421bb14a77a)

Its possible to have only the X for close in the pop up?
Thanks

**Comment by nelsonamen** [comment]
On mobile works 
On fully Kiosk browser dont

**Comment by nelsonamen** [comment]
how i can change the part of the root?

type: custom:bubble-card
card_type: pop-up
hash: '#todasluzes'
state: sensor.luzesligadas
icon: mdi:lightbulb-group
name: ' '
margin_top_mobile: 0px
entity: null
width_desktop: 100%
card_mod:
  style:
    .: |

      ha-card {
        margin-top: 0 !important;
        background: none !important;
        border: none !important;
      }
      .card-content {
        width: 100% !important;
        padding: 0 !important;
      }

      @media only screen and (min-width: 870px)
      
      #root {
          top: calc(100% + 0px + 54px);
          width: calc(100% -92px) !important;
          left: calc(50% - 50% + 0px);
          margin: 0 !important;
      }

**Comment by dsellers1** [comment]
Wanted to throw this in here since it might be related. I noticed the popup at 90% appears *under* the sidebar when it is expanded.
Windows 11, Firefox 116.0, window sizes: 2560x1440 and 1480x1440.
![firefox_QgeKQhtPNE](https://github.com/Clooos/Bubble-Card/assets/67642332/f91cbcfa-080c-4476-8bf1-586007700f34)
I removed the card_modded monstrosity in the screenshot just in case that was somehow messing with it but the results were the same.

When set to 100%, the popup expands up to the collapsed sidebar which could be the area that @nelsonamen showed in his screenshot. Changing to 110% does expand the popup under the collapsed sidebar but then it also pushes the close button off the screen. Attempting to change the z-index of the vertical-stack card via card mod does not bring the popup over the sidebar.

**Comment by nelsonamen** [comment]
width: calc(100% -92px) !important;

- 92px to 0 on the chrome inspector works
How to do this on card mod?

**Comment by samuel9554** [comment]
I think PR #18 could fix this one.

**Comment by Clooos** [comment]
Hi, this is fixed in the new beta with an other approach, but thanks!

**Comment by nelsonamen** [comment]
👍

**Comment by nelsonamen** [comment]
is there a new problem but with right side?
![IMG_20230930_012257](https://github.com/Clooos/Bubble-Card/assets/5807434/902c3a41-1319-49f5-bccf-ef1b8495ce5c)
![IMG_20230930_012309](https://github.com/Clooos/Bubble-Card/assets/5807434/90e9d6cd-2e97-4420-8f2f-e008dc61a2a0)

**Comment by Clooos** [comment]
Indeed! This issue will be fixed in the next beta.

**Comment by Clooos** [comment]
This is now fixed in beta 11 :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.11
