### ISSUE TITLE
Reload issue popped up again

### ISSUE THREAD

**Issue by Nazze** [Clooos/Bubble-Card#342]
**Describe the bug**
The dashboard get into a reload-loop. And then gets stuck. It is the same issue we had previously. It is showing up on all versions of 1.6.x. And a downgrade to 1.5.3. does not seem to work.. 

**To Reproduce**
1. Install version 1.6.3 with HACS
2. Delete cache on all devices
3. Reload the screen on the HA companion app for iOS
4. Error appears (see video)

**Expected behavior**
It should reload once and remain stable

**Screenshots**
https://github.com/Clooos/Bubble-Card/assets/33813707/b7f16f4c-80d4-4491-a2a7-333091605b48

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.2.1
 - Browser HA Companion app (default browser = Firefox)
 - Version 1.6.0, 1.6.2

**Comment by Clooos** [comment]
Hi! I will fix that now once for good! 🍻

**Comment by Nazze** [comment]
Where can I check the current Version of bubble cards? Because I am not sure if the download to 1.5.3. was successful. 
If it was successful, I am not sure, if the latest version of mushroom cards triggers it. Will try to downgrade that, too.

**Comment by Clooos** [comment]
You can check the version in the Bubble Card editor 🙂

**Comment by Nazze** [comment]
Oh yeah, it shows 1.6.1, although I explicitely selected 1.5.3 from HACS. Don't know, if this is an issue with HACS? Will reboot HA now and try again.

**Comment by Nazze** [comment]
I don't know, why HACS was always downloading the latest version, although I picked 1.5.3.
I have overwritten the 2 files in www/comunity_files with the one from github and I could roll-back now to 1.5.3, which is stable for me.

BTW, the version information inside the js file is not correct, that's why it was showing "1.6.1" instead of "1.6.2" in the Bubble Card Editor..

**Comment by Clooos** [comment]
This is fixed in the new 1.6.3!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.3

**Comment by Nazze** [comment]
Yeah, it's not crashing anymore, but the perfomance is slower than 1.5.3. But I understood that you are looking into performance issues https://github.com/Clooos/Bubble-Card/issues/260

**Comment by bexem** [comment]
Thank you for fixing it so quickly! 
It has solved most of the reload issues for me on my iPhone but I’ve noticed that if I have a popup card with a webrtc camera stream in the Lovelace front end it will start the reload loop, to solve it I had to removed those cards (but I’ve kept other with more static content). 
Not a big loss but except some oddities with the 1.5.3 it was working fine before updating to 1.6.x (and it does work fine on desktop).

**Comment by Clooos** [comment]
I've changed something related to the camera pop-ups, it might be the issue. I'm working on it!

**Comment by joaopedros2** [comment]
I am also having the same issue with version 1.6.3.

I have 3 popup cards, where one has 2 camera feeds from Frigate with go2rtc, and the other two have 1 feed each. What happens to me is that sometimes it plays all 4 simultaneously, and sometimes it doesn't open the popup itself...

**Comment by Nazze** [comment]
> This is fixed in the new 1.6.3!
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.3

Hey @Clooos ! I was running 1.6.4. for a day or two, but the reload is still happening. Had to revert to 1.5.3 again, which is stable for me.

**Comment by HAlover99** [comment]
Ciao Cloos,

reload loop it's still present also with the 1.6.4 version.

**Comment by holt3000** [comment]
@Clooos yea I've been having the iOS reload loop still as well. It appeared with 1.6x updates

**Comment by Clooos** [comment]
I'm still actively working on this issue, I will release a new beta as soon as possible.

**Comment by brainstorm82** [comment]
@Clooos I run into this issue and investigated this issue. In my case it starts with a big set of popup elements >10 . When i reduce the popup down to max 10 it is working fine.

**Comment by Clooos** [comment]
Thanks for your feedback, I'm still not sure of what is causing this. Do you have any related logs in Home Assistant or in your HA Companion App logs? I really want to fix that!

**Comment by holt3000** [comment]
In the iOS companion app, going into settings>companion settings>debugging,>reset frontend cache, seemed to help this.

**Comment by HAlover99** [comment]
@holt3000 
i already try without success :(

**Comment by Legrand5382** [comment]
My iPhone do the same, reload loop. Can’t use it at all. I was hoping this update would have fix it but unfortunatly not. I use a iPhone 14 Pro Max with latest IOS. Work perfectly fine on my iPads.

**Comment by Nazze** [comment]
Hi! I had the issue again with 1.7.0, especially when swiping UP. But I cleared the cache a couple of times and I am not seeing it anymore. I hope it stays like this for the next couple of days. But so far, this is the best release, I've seen... I love it, @Clooos !

**Comment by hellomarb** [comment]
Can confirm that heavy dashboards with > 8 popups crash the iOS app scrolling down on my dashboard. When I remove 3 of them all is fine. They contain mini-media-player, apex charts and sankey-chart which are all memory heavy.
So looks like a memory issue on iOS.

**Comment by Gyldenlow** [comment]
Can also confirm that the reload loop is present. Goes away when i limit the number of pop-up cards to a max of 10.

iPhone 15 pro, bubble-card v1.70

**Comment by Clooos** [comment]
Thanks a lot for your feedback everyone, I will try to add more pop-ups on my test dashboard to reproduce this issue.

**Comment by Nazze** [comment]
I actually had the issue today, too. But strangely it recovered and I am able to use the dashboard again. 
iPhone 15 pro and HA companion app. No related logs seen.

**Comment by Nazze** [comment]
Some additional remarks: I had still the pre-1.7.0 style in my dashboard (means, optimized mode and custom:bubble-pop-up). Changed it to the new style added the fix to configuration yaml and rebooted the server. 
Still the reboot was happening. And it was happening with HA companion app and Firefox. Rebooting the iPhone solved for now. It really smells like a memory leak, which seems to affect the OS (closing the apps and restarting and also different apps not working). Only rebooting the iPhone seems to help. And now it is quicker than ever.

**Comment by Clooos** [comment]
This is my guess too, just a question, do you have one or more cameras in your pop-ups? If yes what card do you use for that?

**Comment by Nazze** [comment]
No, I am not using camera cards.

**Comment by Legrand5382** [comment]
No camera also here, a few small pictures on somes.

**Comment by Clooos** [comment]
This issue is my priority right now, I was able to replicate it on my iPad so it's a good start.

**Comment by Gyldenlow** [comment]
No cameras here either. Today I tried restarting my iPhone as suggested by @Nazze, which seemed to fix it for some time.

**Comment by Clooos** [comment]
I've released the new v1.7.1, but I can't say for sure that this is fixed.

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.1

**Comment by Legrand5382** [comment]
Same here, seem to stay longer then before but still go on loop after maybe 3-4 seconds.

**Comment by Clooos** [comment]
Even after clearing the cache / rebooted the iOS device? I really have no more issues.

But if it persists I still have an idea, but I just want to be sure that this is still an issue.

**Comment by Nazze** [comment]
Last time it took a couple of days to show up. So I am still testing. But at the moment 1.7.1 looks stable to me.

**Comment by hellomarb** [comment]
Still an issue (without cameras in popups, but apex-charts + sankey charts + > 8 popups), crash on scroll.
I'm testing in a new copy of my installation, so frontend caching isn't the problem.

**Comment by Clooos** [comment]
I will release a test version here probably today. I might have an idea on how to fix that 🤞

**Comment by Gyldenlow** [comment]
I've had the bug happen only once after updating to 1.7. However, since rebooting my phone it has yet to appear again

**Comment by Clooos** [comment]
Here is a test version that I really hope could fix this issue, just install it with the [Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#without-hacs) installation method.

This version is removing and recreating the content of each pop-ups when they are opened, so in theory even with 1000 pop-ups it should works 🤞 This part of the code was previously used for only removing the videos, so don't use the `background_camera: true` feature in this test version.

[bubble-card.js.zip](https://github.com/Clooos/Bubble-Card/files/14344927/bubble-card.js.zip)

**Comment by hellomarb** [comment]
Yes, I can confirm that in my usecase the reload on scroll bug is solved by the new approach.
I will test it over the day, but for now it seems much faster and bubblecard isn't getting in the way of card_mod anymore while inital load.

Is there a branch with the src so I can build it on my own? 
I put my css modifications in the core bubble-pop.js file to have it global for all popups (z-index issues and a lot of styling).

**Comment by Clooos** [comment]
I will modify this a bit and I will release that as the 1.7.2 version 🙂

**Comment by Clooos** [comment]
The update is now available!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.2

**Comment by Gyldenlow** [comment]
Absolute chad 👆🏻

**Comment by Legrand5382** [comment]
This version work perfectly well on my iPhone (no more reload at all) and also seem faster on my Ipad, thank you for your wonderful work 😊

**Comment by holt3000** [comment]
Thanks @clooos ! Great work

**Comment by Nazze** [comment]
Man, it feels like a big step forward. I will monitor for a couple of days. But I think you deserve more beer already 😅🍻

**Comment by HAlover99** [comment]
Ciao Cloods

Refresh page solved but when try to open a popup-card loop start again.
I already clear cache and reboot iPhone.

**Comment by Clooos** [comment]
I had this issue too, BUT this is already fixed and I will release a new version soon!

**Comment by Clooos** [comment]
This issue is still happening on some setups, bur I've made significant progresses on that. The next release is going to be lightning fast on every setups!

**Comment by Clooos** [comment]
This issue should be finally fixed in the v2 beta! Can anyone confirm this?

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by Nazze** [comment]
So far I did not see it. But I will test for a few days. I recommend to close this ticket and reopen, when it shows up again. The new beta is a great piece of work.

**Comment by thargy** [comment]
This issue has returned after last night's update!

**Comment by Clooos** [comment]
Hi! Interesting, there is probably a memory leak I've missed. Is your dashboard a one page, or do you use multiple page with pop-ups on each?

**Comment by thargy** [comment]
Hi Clooos,

I wanted to share my findings on a redirect loop and console stack-trace crash that started immediately after updating to Bubble-Card v3.2.0.  I spent many hours today trying to capture console logs, the redirection made accessing HA via mobile impossible, but I made progress using the Chrome Dev Console.

### 1. The Startup Redirect Loop
I believe that in v3.2.0, the new pop-up hash handling dispatches a `location-changed` event on startup. 

In environments that use redirect management components (such as the [DEFAULT-DASHBOARD](https://github.com/daredoes/default-dashboard)  custom HACS app), this startup location change triggers Home Assistant's router to re-evaluate the active route and fire a `hass-default-panel` event. This triggers the redirect manager's logic, which rewrites `localStorage.defaultPanel` and forces a reload via `location.replace("/")`, resulting in an infinite page-refresh loop.

Disabling DEFAULT-DASHBOARD stopped the looping, but the following console errors still occur once on page load: 

### 2. Unhandled Promise Rejection & Logger Crash
During page load (and when transitions are aborted due to navigation), the console shows:
```
home:1 Uncaught (in promise) AbortError: Transition was skipped

logging-mixin.ts:78 Failure writing unhandled promise rejection to system log: Error: Cannot parse given Error object
    at Object.parse (error-stack-parser.js:35:23)
    at stacktrace.js:106:62
    at new Promise (<anonymous>)
    at fromError (stacktrace.js:105:20)
    at c (log-message.ts:63:31)
    at logging-mixin.ts:67:33
```
This is because Home Assistant's global listener (`logging-mixin.ts`) intercepts unhandled promise rejections and attempts to parse them using `error-stack-parser.js`. 

In Bubble-Card v3.2.0, the template subscription is registered via `c.subscribeMessage(...)` but has no `.catch()` block. If the subscription fails or is aborted during startup, it triggers an unhandled promise rejection. Because the rejection payload is a raw WebSocket object (or browser DOMException) rather than a standard JS `Error` instance containing a stack trace, the Home Assistant stack parser crashes.

Adding a simple `.catch()` block to the `subscribeMessage` promise in Bubble-Card to handle the rejection safely logs the error to the console and prevents it from bubbling up to the global handler.

### 3. `bubble-modules.yaml` 404 Warning

Finally, on load, Bubble-Card checks for the presence of local custom modules:

```
GET https://home.thargy.com/local/bubble/bubble-modules.yaml 404 (Not Found)
```

This appears benign and handled safely in Bubble-Card's fetch catch block, but it was being flooded in the logs during the redirect loop. It can be silenced by creating an empty file at `/config/www/bubble/bubble-modules.yaml`.

I hope this helps?

**Comment by Clooos** [comment]
The third point is expected when Bubble Card Tools isn't installed and I wanted to improve this error to explain this (and forgot).

For the other points I will check that, thanks Claude for your detailed comment 🫡

**Comment by thargy** [comment]
> thanks Claude for your detailed comment

I'm autistic - not AI :rofl: 

You can check my commits back to 2012 and code from 2008, so either I was a sneaky top-secret AI plant spying on GitHub, or I might just be flesh and blood...

🍿 — emoji and emdash ... who do you believe?

P.S. I can't afford Claude, I'm a poor trainee teacher these days
P.P.S. I do use Grammarly to shorten my massive info dumps. I went through about 8 drafts of the above monster.

**Comment by Clooos** [comment]
Well, impressive and unusual comment then! And like I said, I will check that before releasing v3.2.1 (tomorrow I hope 🤞) and let's hope this will fix your issues! 

Thank you so much for your time!

**Comment by Clooos** [comment]
Hi again! I tried to reproduce this issue without any luck, but I've added the missing `.catch()` in `render-template.js`. For the `location-changed` event on startup, this can only happens if you have a pop-up with an active trigger. Have you tried to reproduce this on a new view with pop-ups and without any triggers? 

I honestly have no idea of what I could change about that, since pop-ups needs this event for being opened.

Also, could you try [my most recent build](https://github.com/Clooos/Bubble-Card/tree/main/dist) that contains this fix? Just remove it from HACS first then follow the [Without HACS](https://github.com/Clooos/Bubble-Card#installation) steps from the documentation (and don't forget to clear your cache after that).

Thank you in advance!

Edit: And for the 404 error I've (finally) added this:

<img width="328" height="138" alt="Image" src="https://github.com/user-attachments/assets/ecb0ba5c-0024-4d98-9c56-9960fe792dbf" />

**Comment by Clooos** [comment]
@thargy Any improvements in v3.2.3?

**Comment by thargy** [comment]
So sorry, was swamped with work, but I've not had a single issue since the update.

Thanks!

**Comment by Clooos** [comment]
I'm glad to read that! Thank you so much for the feedback! 😄
