### ISSUE TITLE
[Feature Request] Support for Fan Entities

### ISSUE THREAD

**Issue by csudderth** [Clooos/Bubble-Card#346]
Would love official support for fan entities in the button card. You can kind of get it to work right now, but there is no speed control.

**Comment by VitaminTe** [comment]
Can you give an example of this implementation? 

Ideally I'd just like to use a slider no different than a light to control the speed of a fan. Currently that does not work. It would also be great to have this functionality for covers (roller blinds).

A few more beers coming your way. Appreciate all of your work, I've been enjoying and supporting since the first release.

**Comment by Clooos** [comment]
I'm working on a new documentation and I will add more exemples.

And indeed I will add the possibility to control a fan with a slider, good idea. Also in the v2 you can now control your covers with the sliders 👌

I have a few bugs to fix but the final release is getting closer! 🎉

**Comment by DerHerzog7** [comment]
+1 for this. I love the way Mushroom card implements fans (particular the animation), but it doesnt match the bubble card aesthetic.

**Comment by Clooos** [comment]
I've never tried Mushroom, what kind of animation is it?

**Comment by DerHerzog7** [comment]
Oh it just makes the fan icon spin when it's on. But it's a nice touch!
