### ISSUE TITLE
Close popup on menu item tap

### ISSUE THREAD

**Issue by nomonkeynodeal** [Clooos/Bubble-Card#36]
I can't even tell you how much I love this card. I wasn't even using all my popups before because browser_mod popups are so slow and unreliable. Now the popups are so much more practical.

I use a lot of mushroom entity cards in the menus. I was thinking it would be great if the menu would close when I press certain items, but not others. Not even sure if this is possible.

Thanks again.

**Comment by Clooos** [comment]
It should be doable but it's seems really difficult to implement, I don't think that I have enough skill for that right now, HA development is so new to me. But thanks for the suggestion and thanks for the really kind words. I will close this for now (because I love closing issues) but I will keep this mind for my future and more skilled self.
