### ISSUE TITLE
Feature Request - Tap actions for separator card

### ISSUE THREAD

**Issue by Daniel-dev22** [Clooos/Bubble-Card#415]
It would be nice to have tap actions on the separator card so it could be tapped on to launch a pop-up for example.

**Comment by sayam93** [comment]
This would be a great addition for those of us who use the separator cards for room names on the main dashboard and want to display only some of those devices under the room name on the main display. Tapping a separator that could open a pop containing all the devices in that room instead of just the ones on the main dashboard would be neat!

**Comment by Clooos** [comment]
I'm working on it for the next release 🍻
