### ISSUE TITLE
[v2.1.0] Unable use navigate on sub-buttons

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#662]
no reaction when tapping the sub button, while this is happening to iOS/iPadOS regardless HA app or browser. No problem on a PC browser.

Not sure if it is happening on my setup only... Any thoughts?

**Comment by Clooos** [comment]
Hi! I also have multiple sub-buttons with the navigate action and I have no issue on iOS, can you share more details about your YAML?

**Comment by Clooos** [comment]
I had a bit of time to take a look at your YAML and I'm not sure of what it is supposed to looks like, it seems that you want to replicate my sub-buttons row but with the large-2-rows layout? 

Have you considered changing your YAML to be more like my example? Because this one is working on iOS for me.
