### ISSUE TITLE
Ceiling Fan Slider

### ISSUE THREAD

**Issue by awluter** [Clooos/Bubble-Card#762]
I have an issue where the slider/fill color stays in the background even when the ceiling fan is turned off.

**To Reproduce**  
1. Turn On Fan Entity
2. Adjust Slider For Fan Speed
3. Turn Off Fan Entity
4. Slider/Fan Speed Indication Does Not Disappear/Turn Off

**Expected behavior**  

**Screenshots**  
I expected this to behave the same as the light (next to it in the screenshot), where the background goes gray when the fan is turned off. 

**Informations (please complete the following information):**  
 - OS: iOs
 - Browser/App: Chrome
 - Bubble Card version: 2.2.4
 - Home Assistant version: 2024.8.3

![Screenshot](https://github.com/user-attachments/assets/bb82d800-1721-4150-a04d-31e37c88358f)
Thank you! 🍻

**Comment by ericmarrone** [comment]
I have the same issue.

**To Reproduce**
Steps to reproduce the behavior:

    1. Turn On Fan Entity
    2. Adjust Slider For Fan Speed
    3. Turn Off Fan Entity
    4. Slider Color and Fan Speed % Does Not Disappear/Turn Off

**Expected behavior**
I expect fan entities to behave like light entities, where slider level and fan speed % disappear when entity is off.

**Screenshots**
<img width="594" alt="Screenshot 2024-10-07 at 1 52 33 AM" src="https://github.com/user-attachments/assets/1b10c07f-d0a9-4c46-8a45-667714084460">
<img width="576" alt="Screenshot 2024-10-07 at 1 52 42 AM" src="https://github.com/user-attachments/assets/eb6dfd8f-416d-40ff-ade6-86f0a20036e9">

**Info**
OS: Android and Mac OS
Browser/App: HA Android App, Firefox, Chrome
Bubble Card version: 2.3.0-beta.2
Home Assistant Core version: 2024.10.1

**Comment by DerHerzog7** [comment]
Same here. It's driving me nuts.

**Comment by Clooos** [comment]
Hi! I forgot to mention this issue in the new changelog, but this issue should be now fixed in the new beta 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.3
