### ISSUE TITLE
v2.3.0-beta.6 Climate card is blue while heating is on

### ISSUE THREAD

**Issue by flz** [Clooos/Bubble-Card#923]
**Describe the bug**  
Using the climate card, card appears blue while heating is on.

**Expected behavior**  
Expecting the card to be orange instead.

**Screenshots**  

<img width="816" alt="Screenshot 2024-11-15 at 7 31 21 PM" src="https://github.com/user-attachments/assets/a2854974-1e04-4194-8e5c-612eb6863bb1">
<img width="706" alt="Screenshot 2024-11-15 at 7 31 41 PM" src="https://github.com/user-attachments/assets/bd2a24bd-0e20-490a-a5e2-7defa689bc61">
<img width="521" alt="Screenshot 2024-11-15 at 7 31 47 PM" src="https://github.com/user-attachments/assets/92346410-2388-4923-bcb8-004b5de7f9d8">

**Informations (please complete the following information):**  
 - OS: Mac OS
 - Browser/App: Chrome
 - Bubble Card version: v2.3.0-beta.5 
 - Home Assistant version: 2024.11.x

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Hi and thank you for the feedback, I will take a look at that.

**Comment by Clooos** [comment]
Everything should work as expected now! 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.7

**Comment by Claeysjens** [comment]
Hello,

Thank you for releasing beta 7 so quickly. Unfortunately, the issue is still present. When set to automatic, it still shows green instead of red when the current action is heating.
![IMG_4320](https://github.com/user-attachments/assets/8fc010de-b5bc-4ede-835d-ddb961284779)
![IMG_4319](https://github.com/user-attachments/assets/50383932-d8fe-4516-8bcb-f4d56327f5ba)

**Comment by Claeysjens** [comment]
Hello,

Thank you for releasing beta 7 so quickly. Unfortunately, the issue is still present. When set to automatic, it still shows green instead of red when the current action is heating.
![IMG_4322](https://github.com/user-attachments/assets/226e4f73-0efa-4c23-beb1-98c714adf5a7)
![IMG_4320](https://github.com/user-attachments/assets/ee13923c-198b-47e8-9b50-4fcb1b4c4c93)

**Comment by Clooos** [comment]
Can you share these infos from the dev tools?

![Screenshot_2024-11-16-16-57-19-509_io homeassistant companion android](https://github.com/user-attachments/assets/f36587a1-d06c-4cf0-9278-973d6698ad16)

**Comment by Claeysjens** [comment]
Sure.

![IMG_4323](https://github.com/user-attachments/assets/779fd7b0-b376-4548-a374-da6e35fcab08)

**Comment by Clooos** [comment]
I should have found the issue here, this was a mistake on my side with the auto mode indeed.

Could you try this version? You need to remove Bubble Card from HACS first, then install it with the "[Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#installation)" method.

[bubble-card.js.zip](https://github.com/user-attachments/files/17791931/bubble-card.js.zip)

Once installed, clear your cache then check in the editor if you see v2.3.0-beta.8.

Thank you in advance! 🤞

**Comment by Claeysjens** [comment]
Hi, the new beta version has solved the problem.
<img width="544" alt="Scherm­afbeelding 2024-11-17 om 20 52 51" src="https://github.com/user-attachments/assets/b9454f7c-610f-4f91-b197-dae90f811980">

**Comment by Clooos** [comment]
Finally, thank you for the feedback! 

This was probably the last remaining issue 🤞
